# Generated by Django 5.1.1 on 2024-11-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imagefour',
        ),
        migrations.AddField(
            model_name='product',
            name='imageone',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='imagethree',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='imagetwo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
